# Generated by Django 5.2.1 on 2025-05-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='titulo',
            field=models.CharField(default='Sobre Mim', max_length=100),
        ),
    ]
